name: Deploy

on:
  push:
    branches:
      - master

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'

      - name: Install Node dependencies
        run: |
          npm config set update-notifier false
          npm install --global --no-audit --no-fund autoprefixer \
                                                    cssnano \
                                                    html-minifier \
                                                    postcss-cli \
                                                    prettier \
                                                    terser

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install ghp-import \
                                git+https://github.com/carnarez/markdown-extension-astdocs@master \
                                git+https://github.com/carnarez/markdown-extension-img@master \
                                git+https://github.com/carnarez/markdown-extension-insert@master \
                                git+https://github.com/carnarez/markdown-extension-script@master \
                                jinja2 \
                                lunr \
                                markdown \
                                pymdown-extensions \
                                pyyaml
          python -m pip install --editable .

      - name: Render Markdown content
        run: |
          (
            cd tests

            find . -name "*.md" | while read f; do mkdir -p /tmp/www/`dirname $f`; done
            render-markdown --meta="title=Cool stuff|description=Testing playground for Markdown rendering." \
                            --prefix=/tmp/www \
                            --template=../markdown_render/template.html \
                            `find . -name "*.md"`
          )

      - name: List articles by their titles (SEO)
        run: |
          (
            cd tests

            ls -1 */index.md | grep -v '^tests/' | while read f; do
              l=`grep -B1000 -E -m2 '^---\s*$' $f | sed -nr 's/^title:\s*(.+)/\L\1/p' | sed 's/ /-/g' | tr -cd '[:alnum:]-'`
              ln -s `dirname $f` $l 2>/dev/null
              mv $l /tmp/www 2>/dev/null
            done
          )

      - name: Prettify via Prettier
        run: |
          (
            cd /tmp/www

            prettier --write .
          )

      - name: Minify via clean-css, html-minifier and terser
        run: |
          (
            git clone --depth=1 https://github.com/carnarez/markdown-render-styling.git

            cd markdown-render-styling

            cat style.css style-*.css | grep -v '@import "' > /tmp/www/style.css
          )
          (
            cd /tmp/www
            
            find . -name "*.css" | while read f; do
              postcss $f --no-map --replace --use autoprefixer
              postcss $f --no-map --replace --use cssnano
            done
            
            find . -name "*.html" | while read f; do
              html-minifier --collapse-boolean-attributes \
                            --collapse-whitespace \
                            --minify-css true \
                            --minify-js true \
                            --output $f \
                            --remove-attribute-quotes \
                            --remove-comments \
                            --remove-empty-attributes \
                            --remove-optional-tags \
                            --remove-redundant-attributes \
                            --remove-script-type-attributes \
                            --remove-style-link-type-attributes \
                            --use-short-doctype \
                            $f
            done
            
            find . -name "*.js" | while read f; do
              terser --compress --mangle --output $f $f
            done
          )

#      - name: Publish to GitHub Pages
#        run: |
#          ghp-import --branch www --force --push /tmp/www
