name: Deploy

on:
  push:
    branches:
      - master

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: Install Node dependencies
        run: |
          npm config set update-notifier false
          npm install --global --no-audit --no-fund autoprefixer \
                                                    clean-css-cli \
                                                    html-minifier \
                                                    postcss-cli \
                                                    prettier \
                                                    terser

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install ghp-import \
                                git+https://github.com/carnarez/markdown-astdocs@master \
                                git+https://github.com/carnarez/markdown-img@master \
                                git+https://github.com/carnarez/markdown-insert@master \
                                git+https://github.com/carnarez/markdown-script@master \
                                jinja2 \
                                lunr \
                                markdown \
                                pymdown-extensions \
                                pyyaml

      - name: Render Markdown content
        run: |
          (
            cd prose

            find . -name "*.md" | while read f; do mkdir -p /tmp/www/`dirname $f`; done
            python ../build/render.py --meta="title=Cool stuff|description=Testing playground for Markdown rendering." \
                                      --prefix=/tmp/www \
                                      --template=../build/template.html \
                                      `find . -name "*.md"`
          )

      - name: List articles by their titles (SEO)
        run: |
          (
            cd prose

            ls -1 */index.md | grep -v '^tests/' | while read f; do
              l=`grep -B1000 -E -m2 '^---\s*$' $f | sed -nr 's/^title:\s*(.+)/\L\1/p' | sed 's/ /-/g' | tr -cd '[:alnum:]-'`
              ln -s `dirname $f` $l 2>/dev/null
              mv $l /tmp/www 2>/dev/null
            done
          )

      - name: Prettify via Prettier
        run: |
          (
            cd /tmp/www

            prettier --write .
          )

      - name: Minify via clean-css, html-minifier and terser
        run: |
          (
            cd static

            cat style.css style-*.css | grep -v '@import "' > /tmp/www/style.css
          )
          (
            cd /tmp/www
            
            find . -name "*.css" | while read f; do
              postcss $f --replace --use autoprefixer
              cleancss --output $f $f
            done
            
            find . -name "*.html" | while read f; do
              html-minifier --collapse-boolean-attributes \
                            --collapse-whitespace \
                            --output $f \
                            --minify-css true \
                            --minify-js true \
                            --remove-attribute-quotes \
                            --remove-comments \
                            --remove-empty-attributes \
                            --remove-optional-tags \
                            --remove-redundant-attributes \
                            --remove-script-type-attributes \
                            --remove-style-link-type-attributes \
                            --use-short-doctype \
                            $f
            done
            
            find . -name "*.js" | while read f; do
              terser --compress --mangle --output $f $f
            done
          )

#      - name: Publish to GitHub Pages
#        run: |
#          ghp-import --branch www --force --no-jekyll --push /tmp/www
